#!/bin/sh

# main script
while [ "${1#-}" != "$1" -a -n "$1" ]; do
    case $1 in
        --dry-run|-n) xeq=echo; shift;;
          --debug|-d) set -x; shift;;
                   *) echo "ignoring unknown option $1..."; shift;;
    esac
done

if test -e /boot/uboot/uboot.env; then
    exit 0
fi

if ! cmp -s "$1/usr/etc/fw_env.config" "$2/usr/etc/fw_env.config"; then
    $xeq "$1/usr/sbin/fw_printenv" -c "$1/usr/etc/fw_env.config" | \
        $xeq mkenvimage -s 131072 -o /boot/uboot/uboot.env
    sync
fi

exit 0
